"""last

Revision ID: 10fb4b1a8822
Revises: ce7a7890d8db
Create Date: 2022-04-23 04:43:36.507491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10fb4b1a8822'
down_revision = 'ce7a7890d8db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hosname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=20), nullable=False))
        batch_op.drop_column('name')
        batch_op.drop_column('cnic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cnic', sa.VARCHAR(length=13), nullable=True))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('hosname')

    # ### end Alembic commands ###
