"""empty message

Revision ID: 837dbc3fb18d
Revises: fe34bdb089ff
Create Date: 2022-04-23 04:33:25.153667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '837dbc3fb18d'
down_revision = 'fe34bdb089ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'blooddonors', 'receivers', ['takenby'], ['id'])
    op.add_column('receivers', sa.Column('hosname', sa.String(length=30), nullable=False))
    op.add_column('receivers', sa.Column('city', sa.String(length=20), nullable=False))
    op.drop_column('receivers', 'cnic')
    op.drop_column('receivers', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receivers', sa.Column('name', sa.VARCHAR(length=20), nullable=True))
    op.add_column('receivers', sa.Column('cnic', sa.VARCHAR(length=13), nullable=True))
    op.drop_column('receivers', 'city')
    op.drop_column('receivers', 'hosname')
    op.drop_constraint(None, 'blooddonors', type_='foreignkey')
    # ### end Alembic commands ###
