"""last

Revision ID: 987ff25527fc
Revises: 10fb4b1a8822
Create Date: 2022-04-24 02:33:53.461371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '987ff25527fc'
down_revision = '10fb4b1a8822'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
