"""last

Revision ID: ce7a7890d8db
Revises: 0ff756472747
Create Date: 2022-04-23 04:36:08.953053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce7a7890d8db'
down_revision = '0ff756472747'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blooddonors', schema=None) as batch_op:
        batch_op.create_foreign_key(None, 'receivers', ['takenby'], ['id'])

    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hosname', sa.String(length=30), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=20), nullable=False))
        batch_op.drop_column('cnic')
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('receivers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=20), nullable=True))
        batch_op.add_column(sa.Column('cnic', sa.VARCHAR(length=13), nullable=True))
        batch_op.drop_column('city')
        batch_op.drop_column('hosname')

    with op.batch_alter_table('blooddonors', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')

    # ### end Alembic commands ###
